#!/usr/bin/env python3
"""Export a compact, answer-first Markdown inventory from graph.db."""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def scalar(connection: sqlite3.Connection, sql: str, parameters: tuple[object, ...] = ()) -> int:
    return int(connection.execute(sql, parameters).fetchone()[0])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=ROOT / "graph" / "graph.db")
    parser.add_argument("--output", type=Path, default=ROOT / "SUMMARY.md")
    args = parser.parse_args()

    connection = sqlite3.connect(args.db)
    connection.row_factory = sqlite3.Row
    counts = {
        "Papers (active)": scalar(connection, "SELECT count(*) FROM papers WHERE publication_status='active'"),
        "Papers (quarantined/inactive)": scalar(connection, "SELECT count(*) FROM papers WHERE publication_status!='active'"),
        "Mechanisms": scalar(connection, "SELECT count(*) FROM entities WHERE kind='mechanism'"),
        "Parameters": scalar(connection, "SELECT count(*) FROM parameters"),
        "Failure modes": scalar(connection, "SELECT count(*) FROM entities WHERE kind='failure_mode'"),
        "Evaluations": scalar(connection, "SELECT count(*) FROM entities WHERE kind='evaluation'"),
        "Evidence items": scalar(connection, "SELECT count(*) FROM evidence"),
        "Nodes": scalar(connection, "SELECT count(*) FROM nodes"),
        "Edges": scalar(connection, "SELECT count(*) FROM edges"),
    }

    lines = [
        "# Knowledge-graph inventory",
        "",
        "**Evidence cutoff:** 2026-08-31  ",
        "**Generated from:** `graph/graph.db`; do not edit this file by hand.",
        "",
        "## Coverage",
        "",
        "| Artifact | Count |",
        "| --- | ---: |",
    ]
    lines.extend(f"| {label} | {count:,} |" for label, count in counts.items())

    lines.extend(["", "## Project-knob coverage", "", "| Knob or boundary | Papers |", "| --- | ---: |"])
    for row in connection.execute(
        """
        SELECT substr(target, 6) AS knob, count(DISTINCT source) AS paper_count
        FROM edges WHERE relation='INFORMS' AND target LIKE 'knob:%'
        GROUP BY target ORDER BY paper_count DESC, knob
        """
    ):
        lines.append(f"| `{row['knob']}` | {row['paper_count']} |")

    lines.extend(["", "## Evidence-source mix", "", "| Source type | Items |", "| --- | ---: |"])
    for row in connection.execute(
        "SELECT evidence_type, count(*) AS item_count FROM evidence GROUP BY evidence_type ORDER BY item_count DESC, evidence_type"
    ):
        lines.append(f"| `{row['evidence_type']}` | {row['item_count']} |")

    lines.extend(
        [
            "",
            "## Paper matrix",
            "",
            "| Paper | Year | Status | Tier | Knobs | Mech. | Params | Failures | Eval | Evidence |",
            "| --- | ---: | --- | --- | --- | ---: | ---: | ---: | ---: | ---: |",
        ]
    )
    query = """
      SELECT p.id, p.title, p.primary_url, p.year, p.publication_status, p.tier, p.knobs_json,
        sum(CASE WHEN e.kind='mechanism' THEN 1 ELSE 0 END) AS mechanism_count,
        sum(CASE WHEN e.kind='failure_mode' THEN 1 ELSE 0 END) AS failure_count,
        sum(CASE WHEN e.kind='evaluation' THEN 1 ELSE 0 END) AS evaluation_count,
        (SELECT count(*) FROM parameters x WHERE x.paper_id=p.id) AS parameter_count,
        (SELECT count(*) FROM evidence v WHERE v.paper_id=p.id) AS evidence_count
      FROM papers p LEFT JOIN entities e ON e.paper_id=p.id
      GROUP BY p.id ORDER BY p.year DESC, p.title
    """
    for row in connection.execute(query):
        knobs = ", ".join(f"`{knob}`" for knob in json.loads(row["knobs_json"]))
        title = row["title"].replace("|", "\\|")
        lines.append(
            f"| [{title}]({row['primary_url']}) (`{row['id']}`) | {row['year']} | {row['publication_status']} | {row['tier']} | {knobs} | "
            f"{row['mechanism_count']} | {row['parameter_count']} | {row['failure_count']} | "
            f"{row['evaluation_count']} | {row['evidence_count']} |"
        )

    lines.extend(
        [
            "",
            "## Fast retrieval",
            "",
            "```bash",
            "python3 scripts/query_graph.py stats",
            "python3 scripts/query_graph.py paper 2511.07820",
            "python3 scripts/query_graph.py neighbors knob:reference_composition --relation INFORMS",
            "python3 scripts/query_graph.py parameters --name horizon",
            "python3 scripts/query_graph.py failures --text recovery",
            "python3 scripts/query_graph.py search 'reward AND feedback'",
            "```",
            "",
        ]
    )
    args.output.write_text("\n".join(lines), encoding="utf-8")
    connection.close()
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
